package Modelo.POJOs;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Envio generated by hbm2java
 */
public class Envio  implements java.io.Serializable {


     private Integer idEnvio;
     private Foro foro;
     private Persona persona;
     private Set mensajes = new HashSet(0);

    public Envio() {
    }

	
    public Envio(Foro foro, Persona persona) {
        this.foro = foro;
        this.persona = persona;
    }
    public Envio(Foro foro, Persona persona, Set mensajes) {
       this.foro = foro;
       this.persona = persona;
       this.mensajes = mensajes;
    }
   
    public Integer getIdEnvio() {
        return this.idEnvio;
    }
    
    public void setIdEnvio(Integer idEnvio) {
        this.idEnvio = idEnvio;
    }
    public Foro getForo() {
        return this.foro;
    }
    
    public void setForo(Foro foro) {
        this.foro = foro;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }




}


