package Modelo.POJOs;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Foro generated by hbm2java
 */
public class Foro  implements java.io.Serializable {


     private Integer idForo;
     private Proyecto proyecto;
     private String descripcion;
     private Set proyectos = new HashSet(0);
     private Set envios = new HashSet(0);

    public Foro() {
    }

	
    public Foro(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Foro(Proyecto proyecto, String descripcion, Set proyectos, Set envios) {
       this.proyecto = proyecto;
       this.descripcion = descripcion;
       this.proyectos = proyectos;
       this.envios = envios;
    }
   
    public Integer getIdForo() {
        return this.idForo;
    }
    
    public void setIdForo(Integer idForo) {
        this.idForo = idForo;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }
    public Set getEnvios() {
        return this.envios;
    }
    
    public void setEnvios(Set envios) {
        this.envios = envios;
    }




}


