package Modelo.POJOs;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1



/**
 * Informe generated by hbm2java
 */
public class Informe  implements java.io.Serializable {


     private Integer idInforme;
     private Proyecto proyecto;
     private byte[] documento;

    public Informe() {
    }

    public Informe(Proyecto proyecto, byte[] documento) {
       this.proyecto = proyecto;
       this.documento = documento;
    }
   
    public Integer getIdInforme() {
        return this.idInforme;
    }
    
    public void setIdInforme(Integer idInforme) {
        this.idInforme = idInforme;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public byte[] getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }




}


