package Modelo.POJOs;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private Envio envio;
     private String contenido;

    public Mensaje() {
    }

    public Mensaje(Envio envio, String contenido) {
       this.envio = envio;
       this.contenido = contenido;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Envio getEnvio() {
        return this.envio;
    }
    
    public void setEnvio(Envio envio) {
        this.envio = envio;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


