package Modelo.POJOs;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProyecto;
     private Foro foro;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private String descripcion;
     private Set informes = new HashSet(0);
     private Set archivoses = new HashSet(0);
     private Set foros = new HashSet(0);
     private Set participacions = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String nombre, Date fechaInicio, Date fechaFin, String descripcion) {
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.descripcion = descripcion;
    }
    public Proyecto(Foro foro, String nombre, Date fechaInicio, Date fechaFin, String descripcion, Set informes, Set archivoses, Set foros, Set participacions) {
       this.foro = foro;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.descripcion = descripcion;
       this.informes = informes;
       this.archivoses = archivoses;
       this.foros = foros;
       this.participacions = participacions;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Foro getForo() {
        return this.foro;
    }
    
    public void setForo(Foro foro) {
        this.foro = foro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getInformes() {
        return this.informes;
    }
    
    public void setInformes(Set informes) {
        this.informes = informes;
    }
    public Set getArchivoses() {
        return this.archivoses;
    }
    
    public void setArchivoses(Set archivoses) {
        this.archivoses = archivoses;
    }
    public Set getForos() {
        return this.foros;
    }
    
    public void setForos(Set foros) {
        this.foros = foros;
    }
    public Set getParticipacions() {
        return this.participacions;
    }
    
    public void setParticipacions(Set participacions) {
        this.participacions = participacions;
    }




}


