package Modelo;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1



/**
 * Archivos generated by hbm2java
 */
public class Archivos  implements java.io.Serializable {


     private Integer idArchivo;
     private Proyecto proyecto;
     private byte[] documento;

    public Archivos() {
    }

    public Archivos(Proyecto proyecto, byte[] documento) {
       this.proyecto = proyecto;
       this.documento = documento;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public byte[] getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(byte[] documento) {
        this.documento = documento;
    }




}


