package Modelo;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    private Integer idPersona;
    private String nombre;
    private String apellidos;
    private String dni;
    private boolean admin;
    private String usuario;
    private String password;
    private Set participacions = new HashSet(0);
    private Set envios = new HashSet(0);

    public Persona() {
    }

    public Persona(String nombre, String apellidos, String dni, boolean admin, String usuario, String password) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.dni = dni;
        this.admin = admin;
        this.usuario = usuario;
        this.password = password;
    }

    public Persona(String nombre, String apellidos, String dni, boolean admin, String usuario, String password, Set participacions, Set envios) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.dni = dni;
        this.admin = admin;
        this.usuario = usuario;
        this.password = password;
        this.participacions = participacions;
        this.envios = envios;
    }

    public Integer getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public boolean isAdmin() {
        return this.admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getParticipacions() {
        return this.participacions;
    }

    public void setParticipacions(Set participacions) {
        this.participacions = participacions;
    }

    public Set getEnvios() {
        return this.envios;
    }

    public void setEnvios(Set envios) {
        this.envios = envios;
    }

}
