package Modelo;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombre;
     private String descripcion;
     private Integer acceso;
     private Set participacions = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String nombre) {
        this.nombre = nombre;
    }
    public Rol(String nombre, String descripcion, Integer acceso, Set participacions) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.acceso = acceso;
       this.participacions = participacions;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Integer acceso) {
        this.acceso = acceso;
    }
    public Set getParticipacions() {
        return this.participacions;
    }
    
    public void setParticipacions(Set participacions) {
        this.participacions = participacions;
    }




}


