package Modelo;
// Generated 09-may-2023 5:43:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private Integer idTarea;
     private Participacion participacion;
     private Tarea tarea;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private boolean completado;
     private Set tareas = new HashSet(0);

    public Tarea() {
    }

	
    public Tarea(Participacion participacion, String nombre, Date fechaInicio, boolean completado) {
        this.participacion = participacion;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.completado = completado;
    }
    public Tarea(Participacion participacion, Tarea tarea, String nombre, String descripcion, Date fechaInicio, Date fechaFin, boolean completado, Set tareas) {
       this.participacion = participacion;
       this.tarea = tarea;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.completado = completado;
       this.tareas = tareas;
    }
   
    public Integer getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(Integer idTarea) {
        this.idTarea = idTarea;
    }
    public Participacion getParticipacion() {
        return this.participacion;
    }
    
    public void setParticipacion(Participacion participacion) {
        this.participacion = participacion;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public boolean isCompletado() {
        return this.completado;
    }
    
    public void setCompletado(boolean completado) {
        this.completado = completado;
    }
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


